

# Job to submit a Ray program from a pod outside a running Ray cluster.
apiVersion: batch/v1
kind: Job
metadata:
  name: ray-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ray
          image: rayproject/ray:latest
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args:
            - "wget https://raw.githubusercontent.com/greatdevaks/pycon-colombia-python-ray/main/estimate_pi.py &&
              python estimate_pi.py"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
